apiVersion: batch/v1
kind: CronJob
metadata:
  name: gcs-backup
spec:
  schedule: "* * * * *"  # Runs every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: gcs-backup
              image: google/cloud-sdk:latest
              command:
              - /bin/sh
              - -c
              - |
                mkdir -p /backup
                kubectl get all --all-namespaces -o yaml > /backup/k8s-resources.yaml
                gcloud auth activate-service-account --key-file=/secrets/key.json
                gsutil cp /backup/k8s-resources.yaml gs://your-backup-bucket/k8s-resources-$(date +\%Y\%m\%d\%H\%M\%S).yaml
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "500m"
                limits:
                  memory: "256Mi"
                  cpu: "1"
              volumeMounts:
              - name: backup-storage
                mountPath: /backup
              - name: gcs-credentials
                mountPath: /secrets
                readOnly: true
          restartPolicy: OnFailure
          volumes:
          - name: backup-storage
            emptyDir: {}
          - name: gcs-credentials
            secret:
              secretName: gcs-credentials