apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gb-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: 34.148.206.53  # change to the external IP of the NGINX controller external IP
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: frontend-service
            port:
              number: 5000
      - pathType: Prefix
        path: /submit
        backend:
          service:
            name: frontend-service
            port:
              number: 5000
