apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gcs-backup-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "replicationcontrollers", "services"]
  verbs: ["list"]
- apiGroups: ["apps"]
  resources: ["daemonsets", "deployments", "replicasets", "statefulsets"]
  verbs: ["list"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["list"]
- apiGroups: ["batch"]
  resources: ["cronjobs", "jobs"]
  verbs: ["list"]