apiVersion: apps/v1
kind: Deployment
metadata:
  name: pkinglot-analyzer-deployment
  labels:
    app: pkinglot-analyzer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pkinglot-analyzer
  template:
    metadata:
      labels:
        app: pkinglot-analyzer
    spec:
      containers:
      - name: pkinglot-analyzer
        image: chrisstefaniak/pkinglot-analyzer2:1.0.4
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /secrets/key.json
        volumeMounts:
        - name: firestore-credentials
          mountPath: /secrets
          readOnly: true
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
      volumes:
      - name: firestore-credentials
        secret:
          secretName: firestore-credentials